# Generated by Django 3.2.7 on 2021-09-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
